# Generated by Django 5.2.3 on 2025-07-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='N/A'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='N/A'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='N/A'),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_sub_keys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='N/A'),
        ),
    ]
