# Generated by Django 5.2.3 on 2025-09-13 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_display_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_daily_likes',
            field=models.IntegerField(default=2),
        ),
    ]
