# Generated by Django 5.2.3 on 2025-07-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active'),
        ),
        migrations.AddField(
            model_name='users',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
